version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - redis
    volumes:
      - ./hello.py:/app/hello.py
    environment:
      - ENVIRONMENT=PROD
      - PORT=8000
      - REDIS_PORT=6379
      - REDIS_DB=0
    networks:
      - connect
    command: python hello.py

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - connect

volumes:
  redis_data:

networks:
  connect: